### ISSUE TITLE
[Bug] Dreamcast CHD games aren't imported

### ISSUE THREAD

**Issue by Immersion95** [alucryd/oxyromon#150]
I can't import any DC games as I encounter this error : 

_PS C:\Users\Sonic\Desktop\DC> oxyromon import-roms .
Processing "Ikaruga (Japan).chd"
CUE file found
Matches "Ikaruga (Japan).cue"
Extracting "Ikaruga (Japan).chd"
Error: SimpleError { err: "Failed to delete \"\\\\?\\C:\\Users\\Sonic\\AppData\\Local\\Temp\\.tmpVWKVVu\\.Ikaruga (Japan).cue\", Le fichier spécifié est introuvable. (os error 2)" }
PS C:\Users\Sonic\Desktop\DC>_

I use latest Oxyromon and chdman 0.266

**Comment by alucryd** [comment]
Thanks for the report. Will have a look this week and release a hotfix.

**Comment by alucryd** [comment]
Seems to be an issue with chdman itself :/
```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.267 (mame0267-dirty)
Warning: --splitbin is required for this specific combination of input disc type and output format, enabling automatically
Input CHD:    WWF Royal Rumble (USA).chd
Output TOC:   test.cue
A track number variable (%t) must be specified in the output bin filename when --splitbin is enabled

Fatal error occurred: 1
```
Not sure I can do anything on my end, if not I'll open an issue upstream.

**Comment by alucryd** [comment]
Or not! Didn't read the message properly, since 0.265 chdman is capable of splitting the resulting bin, meaning I don't have to do it myself anymore \o/
Will need to support older chdman versions though so I'll maintain 2 code paths. I'll whip up sth this week and produce a point release by the end of the week.

**Comment by Immersion95** [comment]
> Or not! Didn't read the message properly, since 0.265 chdman is capable of splitting the resulting bin, meaning I don't have to do it myself anymore \o/ Will need to support older chdman versions though so I'll maintain 2 code paths. I'll whip up sth this week and produce a point release by the end of the week.

I don't think that you need to support older version, you just need to mention the minimal version to use :)

**Comment by alucryd** [comment]
Afraid I do, many distros still ship an older chdman version, I can forbid 0.264 and older for Dreamcast because it's broken, but it works fine for everything else so I should at least keep supporting it for a while.

In any case, it's now fixed in https://github.com/alucryd/oxyromon/commit/9ea8ae5fc4baad0cf04bb289ee455688cb810eaa :)

**Comment by Immersion95** [comment]
I built it the develop branch on Linux as it doesn't build with Windows because of the fuser dependencie.

While it works on some CHD, I still have these errors : 

sonic@Freezerlego:~/Emulation/Image$ oxyromon import-roms . -s "Sega Dreamcast"
Processing "Border Down (Japan).cue"
Matches "Border Down (Japan).cue"
Moving to "/home/sonic/Emulation/Sega - Dreamcast/Border Down (Japan).cue"
Processing "Border Down (Japan).chd"
CUE file not found
Extracting "Border Down (Japan).chd"
Error: SimpleError { err: "Failed to delete \"/tmp/.tmptzpywa/.Border Down (Japan).cue\", No such file or directory (os error 2)" }

It first imports the .cue file correctly but doesn't know how to handle the .chd as the .cue file is missing, weird :p.

**Comment by Immersion95** [comment]
In fact, this is not specific to DC, it also happens on other systems with my Ubuntu (WSL). Don't know what is the issue.

**Comment by alucryd** [comment]
I didn't address this because it should never happen unless people specifically import the cue first. When using `.` or `*` files are imported in alphabetical order, so CHD comes before CUE, or so I thought. Sorting the asterisk glob in code will be easy, not sure about the directory, I was under the impression that the standard lib should already do it under the hood, at least that was what I observed here.

**Comment by Immersion95** [comment]
Yeah don't know what's happening, "*" proccesses it in alphabetical order but there's an error after handling and moving 1 chd.

**Comment by Immersion95** [comment]
The solution that I found was to do this while having no .cue files in the database.

- oxyromon import-roms *.chd

**Comment by alucryd** [comment]
Ah yes, I probably need to support this specific use case though. People might want to import all CUE files beforehand. It will still be required alongside the CHD to import it though, but I shouldn't choke if the CUE already exists.
